[package]
name = "pdb2struct"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
env_logger = "0.11.6"
log = "0.4.26"
pdb = "0.8.0"
